import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ThreeBanner from "../components/ThreeBanner/ThreeBanner";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Three JS APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThreeBanner />

      <section style={{ height: "1000px", background: "rgb(24, 24, 34)" }}>
        hello
      </section>
    </div>
  );
}
